services:
  - type: web
    name: vigo-parking-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: REACT_APP_API_URL
        value: "https://vigo-parking-app.onrender.com"
