services:
  - type: web
    name: vigo-parking-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    healthCheckPath: /api/health
